import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-side-menu',
  templateUrl: './side-menu.component.html',
  styleUrls: ['./side-menu.component.css']
})
export class SideMenuComponent implements OnInit {
  menudata: any[] = []
  constructor() {
    this.menudata = menudata
  }

  ngOnInit(): void {
  }

}

const menudata = [
  {
    title: 'Maintenance Report',
    url: '/maintenance',
    iconurl: '../../assets/svg/bar-chart-2.svg',
    icon: 'fa fa-pie-chart',
    icon_res: 'svg',
    hidden: false,
    roles: ['admin'],
    notification_count: 4,
    isCollapsed: true,
    children: [],
    active: false,
  },
  {
    title: 'Reports',
    url: '',
    iconurl: '../../assets/svg/pie-chart.svg',
    icon: 'fa fa-pie-chart',
    icon_res: 'svg',
    hidden: false,
    roles: ['admin'],
    notification_count: 4,
    isCollapsed: true,
    children: [
      {
        title: 'Order Wise',
        url: '/r1',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Product Wise',
        url: '/r2',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Category Wise',
        url: '/r3',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Store Wise',
        url: '/r4',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Time Wise',
        url: '/r5',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Month Wise Product',
        url: '/r6',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'SPG Wise',
        url: '/r7',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Delivery Order',
        url: '/r8',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Cancel Order',
        url: '/r9',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Product Sales',
        url: '/r10',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Customer List',
        url: '/r11',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Versions List',
        url: '/r12',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Kb2 Ratio',
        url: '/kb2chef',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
    ],
    active: false,
  },
  // {
  //   title: 'Products',
  //   url: '/products',
  //   iconurl: '../../assets/svg/',
  //   icon: 'fa fa-pie-chart',
  //   icon_res: 'svg',
  //   hidden: false,
  //   roles: ['admin'],
  //   notification_count: 4,
  //   isCollapsed: true,
  //   children: [],
  //   active: false,
  // },
  // {
  //   title: 'Denominations',
  //   url: '/m2',
  //   iconurl: '../../assets/svg/cash-register-solid.svg',
  //   icon: 'fa fa-pie-chart',
  //   icon_res: 'svg',
  //   hidden: false,
  //   roles: ['admin'],
  //   notification_count: 4,
  //   isCollapsed: true,
  //   children: [],
  //   active: false,
  // },
  {
    title: 'Enquiry Orders',
    url: '/m1',
    iconurl: '../../assets/svg/shopping-cart.svg',
    icon: 'fa fa-pie-chart',
    icon_res: 'svg',
    hidden: false,
    roles: ['admin'],
    notification_count: 4,
    isCollapsed: true,
    children: [],
    active: false,
  },
  {
    title: 'Order Forensic',
    url: '',
    iconurl: '../../assets/svg/shopping-cart.svg',
    icon: 'fa fa-pie-chart',
    icon_res: 'svg',
    hidden: false,
    roles: ['admin', 'cashier'],
    notification_count: 4,
    isCollapsed: true,
    children: [
      {
        title: 'Sus Orders | Pending Orders',
        url: '/m3',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin', 'cashier'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
    ],
    active: false,
  },
  {
    title: 'Utils',
    url: '',
    iconurl: '../../assets/svg/tool.svg',
    icon: 'fa fa-pie-chart',
    icon_res: 'svg',
    hidden: false,
    roles: ['admin', 'cashier'],
    notification_count: 4,
    isCollapsed: true,
    children: [
      {
        title: 'Transaction List',
        url: '/u1',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin', 'cashier'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
      {
        title: 'Order Manager',
        url: '/u2',
        iconurl: '../../assets/svg/',
        icon: 'fa fa-pie-chart',
        icon_res: 'svg',
        hidden: false,
        roles: ['admin', 'cashier'],
        notification_count: 4,
        isCollapsed: true,
        children: [],
        active: false,
      },
    ],
    active: false,
  },
]